kernel : R (Pixi)

#### Making a CellChat object from the h5ad file

In [1]:
h5ad_file <- "nimlab_0421_cellchat.h5ad"
species <- "mouse"
group_key <- "cell"
data_dir <- "CELLCHAT"

invisible(
  suppressPackageStartupMessages({
    library(circlize)
    library(dotenv)
    library(rprojroot)
    library(CellChat)
    library(ComplexHeatmap)
  })
)

root <- rprojroot::find_root(rprojroot::has_file("pixi.toml"))
env_path <- file.path(root, ".env")
dotenv::load_dot_env(file = env_path)

r_dir <- file.path(root, "R")
r_scripts <- list.files(
  path = r_dir,
  pattern = "\\.R$",
  full.names = TRUE,
  recursive = TRUE
)
r_scripts <- r_scripts[!grepl("install\\.R$", r_scripts)]
invisible(sapply(r_scripts, function(x) try(source(x), silent = TRUE)))

cellchat <- run_cellchat(
  h5ad_file = h5ad_file,
  species = species,
  group_key = group_key,
  data_dir = data_dir
)

base_name <- tools::file_path_sans_ext(h5ad_file)
cellchat_dir <- get_env_dir("CELLCHAT")
cellchat_dir <- file.path(cellchat_dir, base_name)

[1] "Create a CellChat object from a data matrix"

Warning message in CellChat::createCellChat(object = data_input, meta = meta_data, :
“The 'meta$samples' is not a factor. We now force it as a factor!
”

Set cell identities for the new CellChat object
The cell groups used for CellChat analysis are  cluster_astrocyte_0, cluster_astrocyte_1, cluster_astrocyte_2, cluster_astrocyte_3, cluster_astrocyte_4, cluster_BAM, cluster_Basophil, cluster_bcell_0, cluster_bcell_1, cluster_bcell_2, cluster_bcell_3, cluster_bcell_4, cluster_bcell_5, cluster_Endothelial, cluster_ependymal_0, cluster_ependymal_1, cluster_ependymal_2, cluster_ependymal_3, cluster_ependymal_4, cluster_ependymal_5, cluster_ependymal_6, cluster_ependymal_7, cluster_Epithelial, cluster_Erythroblast, cluster_Microglia, cluster_mol_0, cluster_mol_1, cluster_mol_2, cluster_mol_3, cluster_mol_4, cluster_mol_5, cluster_mol_6, cluster_Monocytic, cluster_mregDC, cluster_Neuron, cluster_Neutrophil, cluster_neutrophil_0, cluster_neutrophil_1, cluster_neutrophil_2, cluster_neutrophil_3, cluster_neutrophil_4, cluster_neutrophil_5, cluster_nkcell, cluster_NKcell, cluster_opc_0, cluster_opc_1, cluster_opc_2, cluster_opc_3, cluster_opc_4, cluster_opc_5, cluster_opc_6, cluster_opc_7, cluster_opc_8, cluster_Osteoclast, cluster_pDC, cluster_Pericyte, cluster_PNSNeuron, cluster_RBC, cluster_Satellite, cluster_Schwann, cluster_Tcell, cluster_tcell_0, cluster_tcell_1, cluster_tcell_10, cluster_tcell_2, cluster_tcell_3, cluster_tcell_4, cluster_tcell_5, cluster_tcell_6, cluster_tcell_7, cluster_tcell_8, cluster_tcell_9, cluster_unknown_DC, cluster_VLMC, cluster_VSMC

Genes in CellChat input: 28961

Genes in data.signaling: 1371

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 2.8 GiB”

The number of highly variable ligand-receptor pairs used for signaling inference is 2995

LRsig after identifyOverExpressedInteractions: 2995

triMean is used for calculating the average gene expression per cell group.

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 2.8 GiB”

[1] ">>> Run CellChat on sc/snRNA-seq data <<< [2026-07-12 18:29:35.624279]"
[1] ">>> CellChat inference is done. Parameter values are stored in `object@options$parameter` <<< [2026-07-12 18:58:04.682317]"
The cell-cell communication related with the following cell groups are excluded due to the few number of cells:  cluster_bcell_5, cluster_NKcell, cluster_opc_8, cluster_PNSNeuron, cluster_Satellite, cluster_Tcell ! 	15.7% interactions are removed!

#### If you have saved the CellChat object, you can use it by loading the object with the following code:

In [2]:
rds_file <- "nimlab_0421_cellchat.rds"
group_key <- "cell"

invisible(
  suppressPackageStartupMessages({
    library(circlize)
    library(dotenv)
    library(rprojroot)
    library(CellChat)
    library(ComplexHeatmap)
  })
)

base_name <- tools::file_path_sans_ext(rds_file)
cellchat_dir <- get_env_dir("CELLCHAT")
cellchat_dir <- file.path(cellchat_dir, base_name)

cellchat <- readRDS(file.path(cellchat_dir, rds_file))

#### Visualize the specific Ligand-Receptor interaction using a Chord Diagram

In [2]:
# Identified Ligand-Receptor pairs
cellchat@net$LRs

   [1] "TGFB1_TGFBR1_TGFBR2"
   [2] "TGFB2_TGFBR1_TGFBR2"
   [3] "TGFB3_TGFBR1_TGFBR2"
   [4] "TGFB1_ACVR1B_TGFBR2"
   [5] "TGFB2_ACVR1B_TGFBR2"
   [6] "TGFB3_ACVR1B_TGFBR2"
   [7] "TGFB1_ACVR1_TGFBR1"
   [8] "TGFB2_ACVR1_TGFBR1"
   [9] "TGFB3_ACVR1_TGFBR1"
  [10] "BMP2_BMPR1A_ACVR2A"
  [11] "BMP2_BMPR1A_ACVR2B"
  [12] "BMP2_BMPR1A_BMPR2"
  [13] "BMP2_BMPR1B_BMPR2"
  [14] "BMP4_BMPR1A_ACVR2A"
  [15] "BMP4_BMPR1A_ACVR2B"
  [16] "BMP4_BMPR1A_BMPR2"
  [17] "BMP4_BMPR1B_BMPR2"
  [18] "BMP15_BMPR1B_BMPR2"
  [19] "BMP5_ACVR1_ACVR2A"
  [20] "BMP5_ACVR1_ACVR2B"
  [21] "BMP5_ACVR1_BMPR2"
  [22] "BMP5_BMPR1A_ACVR2A"
  [23] "BMP5_BMPR1A_ACVR2B"
  [24] "BMP5_BMPR1A_BMPR2"
  [25] "BMP5_BMPR1B_BMPR2"
  [26] "BMP6_ACVR1_ACVR2A"
  [27] "BMP6_ACVR1_ACVR2B"
  [28] "BMP6_ACVR1_BMPR2"
  [29] "BMP6_BMPR1A_ACVR2A"
  [30] "BMP6_BMPR1A_ACVR2B"
  [31] "BMP6_BMPR1A_BMPR2"
  [32] "BMP6_BMPR1B_BMPR2"
  [33] "BMP7_ACVR1_ACVR2A"
  [34] "BMP7_ACVR1_ACVR2B"
  [35] "BMP7_ACVR1_BMPR2"
  [36] "BMP7_BMPR1A_ACVR2A"
  [37] "BMP7_BMPR1A_ACVR2B"
  [38] "BMP7_BMPR1A_BMPR2"
  [39] "BMP7_BMPR1B_BMPR2"
  [40] "GDF11_TGFBR1_ACVR2A"
  [41] "GDF11_TGFBR1_ACVR2B"
  [42] "GDF11_ACVR1B_ACVR2B"
  [43] "NRTN_GFRA2"
  [44] "INHBA_ACVR1B_ACVR2A"
  [45] "INHBA_ACVR1B_ACVR2B"
  [46] "WNT3_FZD1_LRP5"
  [47] "WNT3_FZD2_LRP5"
  [48] "WNT3_FZD3_LRP5"
  [49] "WNT3_FZD4_LRP5"
  [50] "WNT3_FZD6_LRP5"
  [51] "WNT3_FZD7_LRP5"
  [52] "WNT3_FZD9_LRP5"
  [53] "WNT4_FZD1_LRP5"
  [54] "WNT4_FZD2_LRP5"
  [55] "WNT4_FZD3_LRP5"
  [56] "WNT4_FZD4_LRP5"
  [57] "WNT4_FZD6_LRP5"
  [58] "WNT4_FZD7_LRP5"
  [59] "WNT4_FZD9_LRP5"
  [60] "WNT6_FZD1_LRP5"
  [61] "WNT6_FZD2_LRP5"
  [62] "WNT6_FZD3_LRP5"
  [63] "WNT6_FZD4_LRP5"
  [64] "WNT6_FZD6_LRP5"
  [65] "WNT6_FZD7_LRP5"
  [66] "WNT6_FZD9_LRP5"
  [67] "WNT7A_FZD1_LRP5"
  [68] "WNT7A_FZD2_LRP5"
  [69] "WNT7A_FZD3_LRP5"
  [70] "WNT7A_FZD4_LRP5"
  [71] "WNT7A_FZD6_LRP5"
  [72] "WNT7A_FZD7_LRP5"
  [73] "WNT7A_FZD9_LRP5"
  [74] "WNT7B_FZD1_LRP5"
  [75] "WNT7B_FZD2_LRP5"
  [76] "WNT7B_FZD3_LRP5"
  [77] "WNT7B_FZD4_LRP5"
  [78] "WNT7B_FZD6_LRP5"
  [79] "WNT7B_FZD7_LRP5"
  [80] "WNT7B_FZD9_LRP5"
  [81] "WNT9A_FZD1_LRP5"
  [82] "WNT9A_FZD2_LRP5"
  [83] "WNT9A_FZD3_LRP5"
  [84] "WNT9A_FZD4_LRP5"
  [85] "WNT9A_FZD6_LRP5"
  [86] "WNT9A_FZD7_LRP5"
  [87] "WNT9A_FZD9_LRP5"
  [88] "WNT3_FZD1_LRP6"
  [89] "WNT3_FZD2_LRP6"
  [90] "WNT3_FZD3_LRP6"
  [91] "WNT3_FZD4_LRP6"
  [92] "WNT3_FZD6_LRP6"
  [93] "WNT3_FZD7_LRP6"
  [94] "WNT3_FZD9_LRP6"
  [95] "WNT4_FZD1_LRP6"
  [96] "WNT4_FZD2_LRP6"
  [97] "WNT4_FZD3_LRP6"
  [98] "WNT4_FZD4_LRP6"
  [99] "WNT4_FZD6_LRP6"
 [100] "WNT4_FZD7_LRP6"
 [101] "WNT4_FZD9_LRP6"
 [102] "WNT6_FZD1_LRP6"
 [103] "WNT6_FZD2_LRP6"
 [104] "WNT6_FZD3_LRP6"
 [105] "WNT6_FZD4_LRP6"
 [106] "WNT6_FZD6_LRP6"
 [107] "WNT6_FZD7_LRP6"
 [108] "WNT6_FZD9_LRP6"
 [109] "WNT7A_FZD1_LRP6"
 [110] "WNT7A_FZD2_LRP6"
 [111] "WNT7A_FZD3_LRP6"
 [112] "WNT7A_FZD4_LRP6"
 [113] "WNT7A_FZD6_LRP6"
 [114] "WNT7A_FZD7_LRP6"
 [115] "WNT7A_FZD9_LRP6"
 [116] "WNT7B_FZD1_LRP6"
 [117] "WNT7B_FZD2_LRP6"
 [118] "WNT7B_FZD3_LRP6"
 [119] "WNT7B_FZD4_LRP6"
 [120] "WNT7B_FZD6_LRP6"
 [121] "WNT7B_FZD7_LRP6"
 [122] "WNT7B_FZD9_LRP6"
 [123] "WNT9A_FZD1_LRP6"
 [124] "WNT9A_FZD2_LRP6"
 [125] "WNT9A_FZD3_LRP6"
 [126] "WNT9A_FZD4_LRP6"
 [127] "WNT9A_FZD6_LRP6"
 [128] "WNT9A_FZD7_LRP6"
 [129] "WNT9A_FZD9_LRP6"
 [130] "WNT5A_FZD1"
 [131] "WNT5A_FZD2"
 [132] "WNT5A_FZD3"
 [133] "WNT5A_FZD4"
 [134] "WNT5A_FZD6"
 [135] "WNT5A_FZD7"
 [136] "WNT5A_FZD9"
 [137] "WNT5A_MCAM"
 [138] "WNT5B_FZD1"
 [139] "WNT5B_FZD2"
 [140] "WNT5B_FZD3"
 [141] "WNT5B_FZD4"
 [142] "WNT5B_FZD6"
 [143] "WNT5B_FZD7"
 [144] "WNT5B_FZD9"
 [145] "WNT11_FZD1"
 [146] "WNT11_FZD2"
 [147] "WNT11_FZD3"
 [148] "WNT11_FZD4"
 [149] "WNT11_FZD6"
 [150] "WNT11_FZD7"
 [151] "WNT11_FZD9"
 [152] "TGFA_EGFR"
 [153] "TGFA_EGFR_ERBB2"
 [154] "AREG_EGFR"
 [155] "AREG_EGFR_ERBB2"
 [156] "BTC_EGFR"
 [157] "BTC_EGFR_ERBB2"
 [158] "BTC_ERBB4"
 [159] "HBEGF_EGFR"
 [160] "HBEGF_EGFR_ERBB2"
 [161] "HBEGF_ERBB4"
 [162] "NRG1_ERBB3"
 [163] "NRG1_ERBB2_ERBB3"
 [164] "NRG1_ERBB4"
 [165] "NRG2_ERBB3"
 [166] "NRG2_ERBB2_ERBB3"
 [167] "NRG2_ERBB4"
 [168] "NRG3_ERBB4"
 [169] "NRG1_ITGAV_ITGB3"
 [170] "FGF1_FGFR1"
 [171] "FGF1_FGFR2"
 [172] "FGF1_FGFR3"
 [173] "FGF1_FGFR4"
 [174] "FGF10_FGFR1"
 [175] "FGF10_FGFR2"
 [176] "FGF18_FGFR1"
 [177] "FGF18_FGFR2"
 [178] "FGF18_FGFR3"
 [179] "FGF18_FGFR4"
 [180] "PDGFA_PDGFRA"
 [181] "PDGFA_PDGFRB"
 [182] "PDGFB_PDGFRA"
 [183] "PDGFB_PDGFRB"
 [184] "PDGFC_PDGFRA"
 [185] "PDGFD_PDGFRB"
 [186] "VEGFA_VEGFR1"
 [187] "VEGFA_VEGFR2"
 [188] "VEGFB_VEGFR1"
 [189] "VEGFD_VEGFR3"
 [190] "VEGFD_VEGFR2"
 [191] "PGF_VEGFR1"
 [192] "VEGFA_VEGFR1R2"
 [193] "VEGFD_VEGFR2R3"
 [194] "IGF1_IGF1R"
 [195] "IGF2_IGF1R"
 [196] "IGF2_IGF2R"
 [197] "IGF1_ITGAV_ITGB3"
 [198] "IGF1_ITGA6_ITGB4"
 [199] "IGF2_ITGAV_ITGB3"
 [200] "IGF2_ITGA6_ITGB4"
 [201] "DHH_PTCH1"
 [202] "SHH_PTCH1"
 [203] "CCL5_CCR1"
 [204] "CCL3_CCR1"
 [205] "CCL9_CCR1"
 [206] "CCL6_CCR1"
 [207] "CCL7_CCR1"
 [208] "CCL6_CCR2"
 [209] "CCL7_CCR2"
 [210] "CCL2_CCR2"
 [211] "CCL12_CCR2"
 [212] "CCL27A_CCR2"
 [213] "CCL4_CCR5"
 [214] "CCL5_CCR5"
 [215] "CCL3_CCR5"
 [216] "CCL25_CCR9"
 [217] "CXCL1_CXCR2"
 [218] "CXCL2_CXCR2"
 [219] "CXCL4_CXCR3"
 [220] "CXCL9_CXCR3"
 [221] "CXCL10_CXCR3"
 [222] "CXCL12_CXCR4"
 [223] "CXCL12_ACKR3"
 [224] "CXCL16_CXCR6"
 [225] "MIF_CD74_CXCR4"
 [226] "MIF_CD74_CD44"
 [227] "MIF_CD74_CXCR2"
 [228] "MIF_ACKR3"
 [229] "CX3CL1_CX3CR1"
 [230] "XCL1_XCR1"
 [231] "CTF1_LIFR_IL6ST"
 [232] "OSM_LIFR_IL6ST"
 [233] "OSM_OSMR_IL6ST"
 [234] "IL1A_IL1R1_IL1RAP"
 [235] "IL1B_IL1R1_IL1RAP"
 [236] "IL36G_IL1RL2_IL1RAP"
 [237] "IL18_IL18R1_IL18RAP"
 [238] "IL34_CSF1R"
 [239] "CSF1_CSF1R"
 [240] "IL16_CD4"
 [241] "IFNG_IFNGR1_IFNGR2"
 [242] "TNF_TNFRSF1A"
 [243] "TNF_TNFRSF1B"
 [244] "FASL_FAS"
 [245] "TNFSF11_TNFRSF11A"
 [246] "TNFSF12_TNFRSF12A"
 [247] "TNFSF9_TNFRSF9"
 [248] "TNFSF13B_TNFRSF13B"
 [249] "TNFSF13B_TNFRSF13C"
 [250] "CD40LG_ITGA5_ITGB1"
 [251] "CD40LG_ITGAM_ITGB2"
 [252] "SPP1_CD44"
 [253] "SPP1_ITGAV_ITGB3"
 [254] "SPP1_ITGAV_ITGB1"
 [255] "SPP1_ITGAV_ITGB5"
 [256] "SPP1_ITGAV_ITGB6"
 [257] "SPP1_ITGA4_ITGB1"
 [258] "SPP1_ITGA9_ITGB1"
 [259] "SPP1_ITGA8_ITGB1"
 [260] "SPP1_ITGA5_ITGB1"
 [261] "NAMPT_ITGA5_ITGB1"
 [262] "ANGPTL1_ITGA1_ITGB1"
 [263] "ANGPTL2_ITGA5_ITGB1"
 [264] "ANGPTL2_TLR4"
 [265] "ANGPTL2_PIRB"
 [266] "ANGPTL1_PIRB"
 [267] "ANGPTL4_ITGA5_ITGB1"
 [268] "ANGPTL4_ITGAV_ITGB3"
 [269] "ANGPTL4_CDH5"
 [270] "ANGPTL4_CDH11"
 [271] "ANGPTL4_SDC1"
 [272] "ANGPTL4_SDC2"
 [273] "ANGPTL4_SDC3"
 [274] "ANGPTL4_SDC4"
 [275] "ANGPT1_TEK"
 [276] "ANGPT2_TEK"
 [277] "ANGPT2_ITGA5_ITGB1"
 [278] "MDK_SDC1"
 [279] "MDK_SDC2"
 [280] "MDK_SDC4"
 [281] "MDK_PTPRZ1"
 [282] "MDK_ITGA4_ITGB1"
 [283] "MDK_ITGA6_ITGB1"
 [284] "MDK_LRP1"
 [285] "MDK_NCL"
 [286] "MDK_ALK"
 [287] "PTN_PTPRZ1"
 [288] "PTN_SDC1"
 [289] "PTN_SDC2"
 [290] "PTN_SDC3"
 [291] "PTN_SDC4"
 [292] "PTN_ITGAV_ITGB3"
 [293] "PTN_NCL"
 [294] "PTN_ALK"
 [295] "AGT_AGTR1A"
 [296] "AGT_AGTR1B"
 [297] "C3_C3AR1"
 [298] "C3_ITGAM_ITGB2"
 [299] "C3_ITGAX_ITGB2"
 [300] "HC_C5AR1"
 [301] "EDN1_EDNRA"
 [302] "EDN3_EDNRA"
 [303] "EDN1_EDNRB"
 [304] "EDN3_EDNRB"
 [305] "NPY_NPY1R"
 [306] "PDYN_OPRD1"
 [307] "PDYN_OPRK1"
 [308] "PDYN_OPRL1"
 [309] "PDYN_OPRM1"
 [310] "PENK_OPRD1"
 [311] "PENK_OPRK1"
 [312] "PENK_OPRL1"
 [313] "PENK_OPRM1"
 [314] "POMC_OPRD1"
 [315] "POMC_OPRK1"
 [316] "POMC_OPRL1"
 [317] "POMC_OPRM1"
 [318] "CTSG_F2R"
 [319] "GZMA_F2R"
 [320] "CTSG_F2RL1"
 [321] "GZMA_F2RL1"
 [322] "CTSG_F2RL2"
 [323] "GZMA_F2RL2"
 [324] "CTSG_PARD3"
 [325] "GZMA_PARD3"
 [326] "ADCYAP1_ADCYAP1R1"
 [327] "NPPC_NPR2"
 [328] "KITL_KIT"
 [329] "LHB_LHCGR"
 [330] "BDNF_NTRK2"
 [331] "FLT3L_FLT3"
 [332] "HGF_MET"
 [333] "NTF3_NTRK1"
 [334] "NTF3_NTRK2"
 [335] "NTF3_NTRK3"
 [336] "NTF5_NTRK2"
 [337] "SEMA3B_NRP1_PLXNA1"
 [338] "SEMA3B_NRP1_PLXNA2"
 [339] "SEMA3B_NRP1_PLXNA3"
 [340] "SEMA3B_NRP1_PLXNA4"
 [341] "SEMA3C_NRP1_PLXNA1"
 [342] "SEMA3C_NRP1_PLXNA2"
 [343] "SEMA3C_NRP1_PLXNA3"
 [344] "SEMA3C_NRP1_PLXNA4"
 [345] "SEMA3D_NRP1_PLXNA1"
 [346] "SEMA3D_NRP1_PLXNA2"
 [347] "SEMA3D_NRP1_PLXNA3"
 [348] "SEMA3D_NRP1_PLXNA4"
 [349] "SEMA3B_NRP2_PLXNA1"
 [350] "SEMA3B_NRP2_PLXNA2"
 [351] "SEMA3B_NRP2_PLXNA3"
 [352] "SEMA3B_NRP2_PLXNA4"
 [353] "SEMA3C_NRP2_PLXNA1"
 [354] "SEMA3C_NRP2_PLXNA2"
 [355] "SEMA3C_NRP2_PLXNA3"
 [356] "SEMA3C_NRP2_PLXNA4"
 [357] "SEMA3D_NRP2_PLXNA1"
 [358] "SEMA3D_NRP2_PLXNA2"
 [359] "SEMA3D_NRP2_PLXNA3"
 [360] "SEMA3D_NRP2_PLXNA4"
 [361] "SEMA3F_NRP2_PLXNA1"
 [362] "SEMA3F_NRP2_PLXNA2"
 [363] "SEMA3F_NRP2_PLXNA3"
 [364] "SEMA3F_NRP2_PLXNA4"
 [365] "SEMA3G_NRP2_PLXNA1"
 [366] "SEMA3G_NRP2_PLXNA2"
 [367] "SEMA3G_NRP2_PLXNA3"
 [368] "SEMA3G_NRP2_PLXNA4"
 [369] "SEMA3C_NRP1_NRP2"
 [370] "SEMA3C_PLXND1"
 [371] "SEMA3E_PLXND1"
 [372] "ANXA1_FPR2"
 [373] "ANXA1_FPR1"
 [374] "ENHO_GPR19"
 [375] "GAS6_AXL"
 [376] "GAS6_MERTK"
 [377] "GAS6_TYRO3"
 [378] "GRN_SORT1"
 [379] "LGALS9_CD45"
 [380] "LGALS9_IGHM"
 [381] "PROS1_AXL"
 [382] "PROS1_TYRO3"
 [383] "PSAP_GPR37L1"
 [384] "PSAP_GPR37"
 [385] "RARRES2_CMKLR1"
 [386] "BTLA_TNFRSF14"
 [387] "LGALS9_HAVCR2"
 [388] "LGALS9_CD44"
 [389] "KLK6_F2R"
 [390] "KLK6_F2RL1"
 [391] "KLK1_F2R"
 [392] "KLK8_F2R"
 [393] "ADM_CALCR_RAMP2"
 [394] "ADM_CALCRL_RAMP2"
 [395] "CALCA_CALCR_RAMP2"
 [396] "CALCA_CALCRL_RAMP2"
 [397] "CALCB_CALCR_RAMP2"
 [398] "CALCB_CALCRL_RAMP2"
 [399] "TAFA4_FPR1"
 [400] "CTSG_FPR1"
 [401] "PTPRS_NTRK3"
 [402] "SLITRK1_PTPRD"
 [403] "SLITRK1_PTPRS"
 [404] "SLITRK2_PTPRD"
 [405] "SLITRK2_PTPRS"
 [406] "SLITRK3_PTPRD"
 [407] "SLITRK4_PTPRS"
 [408] "SLITRK5_PTPRS"
 [409] "BDNF_SORT1"
 [410] "BDNF_NGFR"
 [411] "IGFBP3_TMEM219"
 [412] "LGALS9_BCR_CD45_CD22"
 [413] "LGALS9_P4HB"
 [414] "NRG1_ITGA6_ITGB4"
 [415] "NTF3_NGFR"
 [416] "NTF5_NGFR"
 [417] "SLIT1_ROBO1"
 [418] "SLIT2_ROBO1"
 [419] "SLIT2_ROBO2"
 [420] "TUB_MERTK"
 [421] "PROS1_MERTK"
 [422] "PLAU_PLAUR"
 [423] "COL1A1_ITGA1_ITGB1"
 [424] "COL1A2_ITGA1_ITGB1"
 [425] "COL4A1_ITGA1_ITGB1"
 [426] "COL4A2_ITGA1_ITGB1"
 [427] "COL4A5_ITGA1_ITGB1"
 [428] "COL4A6_ITGA1_ITGB1"
 [429] "COL6A1_ITGA1_ITGB1"
 [430] "COL6A2_ITGA1_ITGB1"
 [431] "COL6A3_ITGA1_ITGB1"
 [432] "COL9A2_ITGA1_ITGB1"
 [433] "COL9A3_ITGA1_ITGB1"
 [434] "COL1A1_ITGA2_ITGB1"
 [435] "COL1A2_ITGA2_ITGB1"
 [436] "COL4A1_ITGA2_ITGB1"
 [437] "COL4A2_ITGA2_ITGB1"
 [438] "COL4A5_ITGA2_ITGB1"
 [439] "COL4A6_ITGA2_ITGB1"
 [440] "COL6A1_ITGA2_ITGB1"
 [441] "COL6A2_ITGA2_ITGB1"
 [442] "COL6A3_ITGA2_ITGB1"
 [443] "COL9A2_ITGA2_ITGB1"
 [444] "COL9A3_ITGA2_ITGB1"
 [445] "FN1_ITGA3_ITGB1"
 [446] "FN1_ITGA4_ITGB1"
 [447] "FN1_ITGA5_ITGB1"
 [448] "FN1_ITGA8_ITGB1"
 [449] "LAMA2_ITGA1_ITGB1"
 [450] "LAMA3_ITGA1_ITGB1"
 [451] "LAMA4_ITGA1_ITGB1"
 [452] "LAMA5_ITGA1_ITGB1"
 [453] "LAMB1_ITGA1_ITGB1"
 [454] "LAMB2_ITGA1_ITGB1"
 [455] "LAMC1_ITGA1_ITGB1"
 [456] "LAMC2_ITGA1_ITGB1"
 [457] "LAMC3_ITGA1_ITGB1"
 [458] "LAMA2_ITGA2_ITGB1"
 [459] "LAMA3_ITGA2_ITGB1"
 [460] "LAMA4_ITGA2_ITGB1"
 [461] "LAMA5_ITGA2_ITGB1"
 [462] "LAMB1_ITGA2_ITGB1"
 [463] "LAMB2_ITGA2_ITGB1"
 [464] "LAMC1_ITGA2_ITGB1"
 [465] "LAMC2_ITGA2_ITGB1"
 [466] "LAMC3_ITGA2_ITGB1"
 [467] "LAMA2_ITGA3_ITGB1"
 [468] "LAMA3_ITGA3_ITGB1"
 [469] "LAMA4_ITGA3_ITGB1"
 [470] "LAMA5_ITGA3_ITGB1"
 [471] "LAMB1_ITGA3_ITGB1"
 [472] "LAMB2_ITGA3_ITGB1"
 [473] "LAMC1_ITGA3_ITGB1"
 [474] "LAMC2_ITGA3_ITGB1"
 [475] "LAMC3_ITGA3_ITGB1"
 [476] "RELN_ITGA3_ITGB1"
 [477] "THBS1_ITGA3_ITGB1"
 [478] "THBS2_ITGA3_ITGB1"
 [479] "THBS3_ITGA3_ITGB1"
 [480] "COL1A1_ITGA3_ITGB1"
 [481] "COL1A2_ITGA3_ITGB1"
 [482] "COL4A1_ITGA3_ITGB1"
 [483] "COL4A2_ITGA3_ITGB1"
 [484] "COL4A5_ITGA3_ITGB1"
 [485] "COL4A6_ITGA3_ITGB1"
 [486] "COL6A1_ITGA3_ITGB1"
 [487] "COL6A2_ITGA3_ITGB1"
 [488] "COL6A3_ITGA3_ITGB1"
 [489] "COL9A2_ITGA3_ITGB1"
 [490] "COL9A3_ITGA3_ITGB1"
 [491] "LAMA2_ITGA6_ITGB1"
 [492] "LAMA3_ITGA6_ITGB1"
 [493] "LAMA4_ITGA6_ITGB1"
 [494] "LAMA5_ITGA6_ITGB1"
 [495] "LAMB1_ITGA6_ITGB1"
 [496] "LAMB2_ITGA6_ITGB1"
 [497] "LAMC1_ITGA6_ITGB1"
 [498] "LAMC2_ITGA6_ITGB1"
 [499] "LAMC3_ITGA6_ITGB1"
 [500] "LAMA2_ITGA7_ITGB1"
 [501] "LAMA3_ITGA7_ITGB1"
 [502] "LAMA4_ITGA7_ITGB1"
 [503] "LAMA5_ITGA7_ITGB1"
 [504] "LAMB1_ITGA7_ITGB1"
 [505] "LAMB2_ITGA7_ITGB1"
 [506] "LAMC1_ITGA7_ITGB1"
 [507] "LAMC2_ITGA7_ITGB1"
 [508] "LAMC3_ITGA7_ITGB1"
 [509] "VTN_ITGA8_ITGB1"
 [510] "TNC_ITGA8_ITGB1"
 [511] "TNR_ITGA8_ITGB1"
 [512] "TNXB_ITGA8_ITGB1"
 [513] "TNC_ITGA9_ITGB1"
 [514] "TNR_ITGA9_ITGB1"
 [515] "TNXB_ITGA9_ITGB1"
 [516] "COL1A1_ITGA9_ITGB1"
 [517] "COL1A2_ITGA9_ITGB1"
 [518] "COL4A1_ITGA9_ITGB1"
 [519] "COL4A2_ITGA9_ITGB1"
 [520] "COL4A5_ITGA9_ITGB1"
 [521] "COL4A6_ITGA9_ITGB1"
 [522] "COL6A1_ITGA9_ITGB1"
 [523] "COL6A2_ITGA9_ITGB1"
 [524] "COL6A3_ITGA9_ITGB1"
 [525] "COL9A2_ITGA9_ITGB1"
 [526] "COL9A3_ITGA9_ITGB1"
 [527] "LAMA2_ITGA9_ITGB1"
 [528] "LAMA3_ITGA9_ITGB1"
 [529] "LAMA4_ITGA9_ITGB1"
 [530] "LAMA5_ITGA9_ITGB1"
 [531] "LAMB1_ITGA9_ITGB1"
 [532] "LAMB2_ITGA9_ITGB1"
 [533] "LAMC1_ITGA9_ITGB1"
 [534] "LAMC2_ITGA9_ITGB1"
 [535] "LAMC3_ITGA9_ITGB1"
 [536] "FN1_ITGAV_ITGB1"
 [537] "VTN_ITGAV_ITGB1"
 [538] "FN1_ITGA4_ITGB7"
 [539] "FN1_ITGAV_ITGB3"
 [540] "VTN_ITGAV_ITGB3"
 [541] "VWF_ITGAV_ITGB3"
 [542] "TNC_ITGAV_ITGB3"
 [543] "TNR_ITGAV_ITGB3"
 [544] "TNXB_ITGAV_ITGB3"
 [545] "THBS1_ITGAV_ITGB3"
 [546] "THBS2_ITGAV_ITGB3"
 [547] "THBS3_ITGAV_ITGB3"
 [548] "VTN_ITGAV_ITGB5"
 [549] "TNC_ITGAV_ITGB6"
 [550] "TNR_ITGAV_ITGB6"
 [551] "TNXB_ITGAV_ITGB6"
 [552] "FN1_ITGAV_ITGB6"
 [553] "VTN_ITGAV_ITGB8"
 [554] "FN1_ITGAV_ITGB8"
 [555] "LAMA2_ITGAV_ITGB8"
 [556] "LAMA3_ITGAV_ITGB8"
 [557] "LAMA4_ITGAV_ITGB8"
 [558] "LAMA5_ITGAV_ITGB8"
 [559] "LAMB1_ITGAV_ITGB8"
 [560] "LAMB2_ITGAV_ITGB8"
 [561] "LAMC1_ITGAV_ITGB8"
 [562] "LAMC2_ITGAV_ITGB8"
 [563] "LAMC3_ITGAV_ITGB8"
 [564] "COL1A1_ITGAV_ITGB8"
 [565] "COL1A2_ITGAV_ITGB8"
 [566] "COL4A1_ITGAV_ITGB8"
 [567] "COL4A2_ITGAV_ITGB8"
 [568] "COL4A5_ITGAV_ITGB8"
 [569] "COL4A6_ITGAV_ITGB8"
 [570] "COL6A1_ITGAV_ITGB8"
 [571] "COL6A2_ITGAV_ITGB8"
 [572] "COL6A3_ITGAV_ITGB8"
 [573] "COL9A2_ITGAV_ITGB8"
 [574] "COL9A3_ITGAV_ITGB8"
 [575] "LAMA2_ITGA6_ITGB4"
 [576] "LAMA3_ITGA6_ITGB4"
 [577] "LAMA4_ITGA6_ITGB4"
 [578] "LAMA5_ITGA6_ITGB4"
 [579] "LAMB1_ITGA6_ITGB4"
 [580] "LAMB2_ITGA6_ITGB4"
 [581] "LAMC1_ITGA6_ITGB4"
 [582] "LAMC2_ITGA6_ITGB4"
 [583] "LAMC3_ITGA6_ITGB4"
 [584] "FN1_CD44"
 [585] "COL1A1_CD44"
 [586] "COL1A2_CD44"
 [587] "COL4A1_CD44"
 [588] "COL4A2_CD44"
 [589] "COL4A5_CD44"
 [590] "COL4A6_CD44"
 [591] "COL6A1_CD44"
 [592] "COL6A2_CD44"
 [593] "COL6A3_CD44"
 [594] "COL9A2_CD44"
 [595] "COL9A3_CD44"
 [596] "LAMA2_CD44"
 [597] "LAMA3_CD44"
 [598] "LAMA4_CD44"
 [599] "LAMA5_CD44"
 [600] "LAMB1_CD44"
 [601] "LAMB2_CD44"
 [602] "LAMC1_CD44"
 [603] "LAMC2_CD44"
 [604] "LAMC3_CD44"
 [605] "COL1A1_SDC1"
 [606] "COL1A2_SDC1"
 [607] "COL4A1_SDC1"
 [608] "COL4A2_SDC1"
 [609] "COL4A5_SDC1"
 [610] "COL4A6_SDC1"
 [611] "COL6A1_SDC1"
 [612] "COL6A2_SDC1"
 [613] "COL6A3_SDC1"
 [614] "COL9A2_SDC1"
 [615] "COL9A3_SDC1"
 [616] "FN1_SDC1"
 [617] "TNC_SDC1"
 [618] "TNR_SDC1"
 [619] "TNXB_SDC1"
 [620] "THBS1_SDC1"
 [621] "THBS2_SDC1"
 [622] "THBS3_SDC1"
 [623] "COL1A1_SDC4"
 [624] "COL1A2_SDC4"
 [625] "COL4A1_SDC4"
 [626] "COL4A2_SDC4"
 [627] "COL4A5_SDC4"
 [628] "COL4A6_SDC4"
 [629] "COL6A1_SDC4"
 [630] "COL6A2_SDC4"
 [631] "COL6A3_SDC4"
 [632] "COL9A2_SDC4"
 [633] "COL9A3_SDC4"
 [634] "FN1_SDC4"
 [635] "TNC_SDC4"
 [636] "TNR_SDC4"
 [637] "TNXB_SDC4"
 [638] "THBS1_SDC4"
 [639] "THBS2_SDC4"
 [640] "THBS3_SDC4"
 [641] "LAMA2_SV2A"
 [642] "LAMA3_SV2A"
 [643] "LAMA4_SV2A"
 [644] "LAMA5_SV2A"
 [645] "LAMB1_SV2A"
 [646] "LAMB2_SV2A"
 [647] "LAMC1_SV2A"
 [648] "LAMC2_SV2A"
 [649] "LAMC3_SV2A"
 [650] "LAMA2_SV2C"
 [651] "LAMA3_SV2C"
 [652] "LAMA4_SV2C"
 [653] "LAMA5_SV2C"
 [654] "LAMB1_SV2C"
 [655] "LAMB2_SV2C"
 [656] "LAMC1_SV2C"
 [657] "LAMC2_SV2C"
 [658] "LAMC3_SV2C"
 [659] "THBS1_CD36"
 [660] "THBS2_CD36"
 [661] "THBS3_CD36"
 [662] "THBS1_CD47"
 [663] "THBS2_CD47"
 [664] "THBS3_CD47"
 [665] "AGRN_DAG1"
 [666] "HSPG2_DAG1"
 [667] "LAMA2_DAG1"
 [668] "LAMA3_DAG1"
 [669] "LAMA4_DAG1"
 [670] "LAMA5_DAG1"
 [671] "LAMB1_DAG1"
 [672] "LAMB2_DAG1"
 [673] "LAMC1_DAG1"
 [674] "LAMC2_DAG1"
 [675] "LAMC3_DAG1"
 [676] "VTN_PLAUR"
 [677] "RELN_LRP8"
 [678] "RELN_VLDLR"
 [679] "GABA-A-GAD1_SLC32A1_GABR_A1B3G2"
 [680] "GABA-A-GAD1_SLC32A1_GABR_A1B2"
 [681] "GABA-A-GAD1_SLC32A1_GABR_A1B3"
 [682] "GABA-A-GAD1_SLC32A1_GABR_A2B3G2"
 [683] "GABA-A-GAD1_SLC32A1_GABR_A3B3G2"
 [684] "GABA-A-GAD1_SLC6A1_GABR_A1B3G2"
 [685] "GABA-A-GAD1_SLC6A1_GABR_A1B2"
 [686] "GABA-A-GAD1_SLC6A1_GABR_A1B3"
 [687] "GABA-A-GAD1_SLC6A1_GABR_A2B3G2"
 [688] "GABA-A-GAD1_SLC6A1_GABR_A3B3G2"
 [689] "GABA-A-GAD1_SLC6A11_GABR_A1B3G2"
 [690] "GABA-A-GAD1_SLC6A11_GABR_A1B2"
 [691] "GABA-A-GAD1_SLC6A11_GABR_A1B3"
 [692] "GABA-A-GAD1_SLC6A11_GABR_A2B3G2"
 [693] "GABA-A-GAD1_SLC6A11_GABR_A3B3G2"
 [694] "GABA-A-GAD1_SLC6A6_GABR_A1B3G2"
 [695] "GABA-A-GAD1_SLC6A6_GABR_A1B2"
 [696] "GABA-A-GAD1_SLC6A6_GABR_A1B3"
 [697] "GABA-A-GAD1_SLC6A6_GABR_A2B3G2"
 [698] "GABA-A-GAD1_SLC6A6_GABR_A3B3G2"
 [699] "GABA-A-GAD1_SLC6A8_GABR_A1B3G2"
 [700] "GABA-A-GAD1_SLC6A8_GABR_A1B2"
 [701] "GABA-A-GAD1_SLC6A8_GABR_A1B3"
 [702] "GABA-A-GAD1_SLC6A8_GABR_A2B3G2"
 [703] "GABA-A-GAD1_SLC6A8_GABR_A3B3G2"
 [704] "GABA-A-GAD2_SLC32A1_GABR_A1B3G2"
 [705] "GABA-A-GAD2_SLC32A1_GABR_A1B2"
 [706] "GABA-A-GAD2_SLC32A1_GABR_A1B3"
 [707] "GABA-A-GAD2_SLC32A1_GABR_A2B3G2"
 [708] "GABA-A-GAD2_SLC32A1_GABR_A3B3G2"
 [709] "GABA-A-GAD2_SLC6A1_GABR_A1B3G2"
 [710] "GABA-A-GAD2_SLC6A1_GABR_A1B2"
 [711] "GABA-A-GAD2_SLC6A1_GABR_A1B3"
 [712] "GABA-A-GAD2_SLC6A1_GABR_A2B3G2"
 [713] "GABA-A-GAD2_SLC6A1_GABR_A3B3G2"
 [714] "GABA-A-GAD2_SLC6A11_GABR_A1B3G2"
 [715] "GABA-A-GAD2_SLC6A11_GABR_A1B2"
 [716] "GABA-A-GAD2_SLC6A11_GABR_A1B3"
 [717] "GABA-A-GAD2_SLC6A11_GABR_A2B3G2"
 [718] "GABA-A-GAD2_SLC6A11_GABR_A3B3G2"
 [719] "GABA-A-GAD2_SLC6A6_GABR_A1B3G2"
 [720] "GABA-A-GAD2_SLC6A6_GABR_A1B2"
 [721] "GABA-A-GAD2_SLC6A6_GABR_A1B3"
 [722] "GABA-A-GAD2_SLC6A6_GABR_A2B3G2"
 [723] "GABA-A-GAD2_SLC6A6_GABR_A3B3G2"
 [724] "Glycine-Gly-SHMT2_SLC6A9_GLR_A1B"
 [725] "Adenosine-ADO-NT5E_SLC29A1_ADORA1"
 [726] "Adenosine-ADO-NT5E_SLC29A3_ADORA1"
 [727] "Adenosine-ADO-NT5E_SLC29A4_ADORA1"
 [728] "Adenosine-ADO-NT5E_SLC29A1_ADORA2A"
 [729] "Adenosine-ADO-NT5E_SLC29A3_ADORA2A"
 [730] "Adenosine-ADO-NT5E_SLC29A4_ADORA2A"
 [731] "Adenosine-ADO-NT5E_SLC29A1_ADORA2B"
 [732] "Adenosine-ADO-NT5E_SLC29A3_ADORA2B"
 [733] "Adenosine-ADO-NT5E_SLC29A4_ADORA2B"
 [734] "LTD4-GGT1_CYSLTR1"
 [735] "LTE4-DPEP1_CYSLTR1"
 [736] "LTE4-DPEP2_CYSLTR1"
 [737] "LTD4-GGT1_CYSLTR2"
 [738] "LTE4-DPEP1_CYSLTR2"
 [739] "LTE4-DPEP2_CYSLTR2"
 [740] "LipoxinA4-ALOX12_FPR2"
 [741] "GABA-B-GAD1_SLC32A1_GABBR1"
 [742] "GABA-B-GAD1_SLC6A1_GABBR1"
 [743] "GABA-B-GAD1_SLC6A11_GABBR1"
 [744] "GABA-B-GAD1_SLC6A6_GABBR1"
 [745] "GABA-B-GAD1_SLC6A8_GABBR1"
 [746] "GABA-B-GAD2_SLC32A1_GABBR1"
 [747] "GABA-B-GAD2_SLC6A1_GABBR1"
 [748] "GABA-B-GAD2_SLC6A11_GABBR1"
 [749] "GABA-B-GAD2_SLC6A6_GABBR1"
 [750] "GABA-B-GAD1_SLC32A1_GABBR2"
 [751] "GABA-B-GAD1_SLC6A1_GABBR2"
 [752] "GABA-B-GAD1_SLC6A11_GABBR2"
 [753] "GABA-B-GAD1_SLC6A6_GABBR2"
 [754] "GABA-B-GAD1_SLC6A8_GABBR2"
 [755] "GABA-B-GAD2_SLC32A1_GABBR2"
 [756] "GABA-B-GAD2_SLC6A1_GABBR2"
 [757] "GABA-B-GAD2_SLC6A11_GABBR2"
 [758] "GABA-B-GAD2_SLC6A6_GABBR2"
 [759] "Glutamate-Glu-SLC17A6_GLS_GRIA1"
 [760] "Glutamate-Glu-SLC17A8_GLS_GRIA1"
 [761] "Glutamate-Glu-SLC1A1_GLS_GRIA1"
 [762] "Glutamate-Glu-SLC1A2_GLS_GRIA1"
 [763] "Glutamate-Glu-SLC1A3_GLS_GRIA1"
 [764] "Glutamate-Glu-SLC1A6_GLS_GRIA1"
 [765] "Glutamate-Glu-SLC17A6_GLS2_GRIA1"
 [766] "Glutamate-Glu-SLC17A8_GLS2_GRIA1"
 [767] "Glutamate-Glu-SLC1A6_GLS2_GRIA1"
 [768] "Glutamate-Glu-SLC17A6_GLS_GRIA2"
 [769] "Glutamate-Glu-SLC17A8_GLS_GRIA2"
 [770] "Glutamate-Glu-SLC1A1_GLS_GRIA2"
 [771] "Glutamate-Glu-SLC1A2_GLS_GRIA2"
 [772] "Glutamate-Glu-SLC1A3_GLS_GRIA2"
 [773] "Glutamate-Glu-SLC1A6_GLS_GRIA2"
 [774] "Glutamate-Glu-SLC17A6_GLS2_GRIA2"
 [775] "Glutamate-Glu-SLC17A8_GLS2_GRIA2"
 [776] "Glutamate-Glu-SLC1A6_GLS2_GRIA2"
 [777] "Glutamate-Glu-SLC17A6_GLS_GRIA3"
 [778] "Glutamate-Glu-SLC17A8_GLS_GRIA3"

#### Identify

In [10]:
remove_groups <- c("cluster_PNSNeuron", "cluster_Schwann", "cluster_Osteoclast")
target_groups <- c("cluster_neutrophil_2")

group_order <- sort(levels(cellchat@idents))
group_order <- setdiff(group_order, remove_groups)

mat_count <- cellchat@net$count[group_order, group_order, drop = FALSE]
mat_weight <- cellchat@net$weight[group_order, group_order, drop = FALSE]

pair_count <- as.data.frame(as.table(mat_count), stringsAsFactors = FALSE)
colnames(pair_count) <- c("source", "target", "count")

pair_weight <- as.data.frame(as.table(mat_weight), stringsAsFactors = FALSE)
colnames(pair_weight) <- c("source", "target", "weight")

pair_directed <- merge(
  pair_count,
  pair_weight,
  by = c("source", "target")
)

if (length(target_groups) > 0) {
  pair_directed <- pair_directed[
    pair_directed$source %in% target_groups | pair_directed$target %in% target_groups, 
  ]
}

pair_directed <- pair_directed[
  pair_directed$count > 0 &
    pair_directed$source != pair_directed$target,
]

pair_directed <- pair_directed[
  order(pair_directed$count, pair_directed$weight, decreasing = TRUE),
]

pair_undirected <- transform(
  pair_directed,
  cell1 = pmin(source, target),
  cell2 = pmax(source, target)
)

pair_undirected <- aggregate(
  cbind(count, weight) ~ cell1 + cell2,
  data = pair_undirected,
  FUN = sum
)

pair_undirected <- pair_undirected[
  order(pair_undirected$weight, pair_undirected$count, decreasing = TRUE),
]

head(pair_undirected, 50)

   cell1                cell2                count weight
37 cluster_neutrophil_1 cluster_neutrophil_2 52    2.8217199
32 cluster_Monocytic    cluster_neutrophil_2 69    2.3141450
36 cluster_neutrophil_0 cluster_neutrophil_2 40    2.1886998
38 cluster_neutrophil_2 cluster_neutrophil_3 43    2.0402817
40 cluster_neutrophil_2 cluster_neutrophil_5 30    1.8513047
6  cluster_BAM          cluster_neutrophil_2 44    1.6999849
35 cluster_Neutrophil   cluster_neutrophil_2 41    1.5789302
24 cluster_Microglia    cluster_neutrophil_2 43    1.4934019
65 cluster_neutrophil_2 cluster_VLMC         53    1.3966746
39 cluster_neutrophil_2 cluster_neutrophil_4 35    1.3810526
13 cluster_Endothelial  cluster_neutrophil_2 43    1.2122579
41 cluster_neutrophil_2 cluster_nkcell       40    1.1946614
55 cluster_neutrophil_2 cluster_tcell_10     23    1.1765208
63 cluster_neutrophil_2 cluster_tcell_9      32    1.1350063
60 cluster_neutrophil_2 cluster_tcell_6      39    1.0863677
61 cluster_neutrophil_2 cluster_tcell_7      40    1.0722369
51 cluster_neutrophil_2 cluster_Pericyte     30    1.0436110
62 cluster_neutrophil_2 cluster_tcell_8      46    1.0255977
57 cluster_neutrophil_2 cluster_tcell_3      56    1.0227352
53 cluster_neutrophil_2 cluster_tcell_0      38    0.9773681
56 cluster_neutrophil_2 cluster_tcell_2      38    0.9542629
59 cluster_neutrophil_2 cluster_tcell_5      41    0.9500140
50 cluster_neutrophil_2 cluster_pDC          36    0.9364898
33 cluster_mregDC       cluster_neutrophil_2 21    0.8294376
64 cluster_neutrophil_2 cluster_unknown_DC   36    0.7895576
58 cluster_neutrophil_2 cluster_tcell_4      38    0.6938063
11 cluster_bcell_3      cluster_neutrophil_2 21    0.6854407
22 cluster_Epithelial   cluster_neutrophil_2 44    0.6737696
66 cluster_neutrophil_2 cluster_VSMC         31    0.6638638
43 cluster_neutrophil_2 cluster_opc_1        36    0.6624129
30 cluster_mol_5        cluster_neutrophil_2 24    0.6292284
31 cluster_mol_6        cluster_neutrophil_2 24    0.6230116
17 cluster_ependymal_3  cluster_neutrophil_2 45    0.6222509
28 cluster_mol_3        cluster_neutrophil_2 20    0.6219475
10 cluster_bcell_2      cluster_neutrophil_2 13    0.6175976
42 cluster_neutrophil_2 cluster_opc_0        36    0.6056941
29 cluster_mol_4        cluster_neutrophil_2 26    0.5999851
48 cluster_neutrophil_2 cluster_opc_6        37    0.5937943
49 cluster_neutrophil_2 cluster_opc_7        29    0.5873635
26 cluster_mol_1        cluster_neutrophil_2 21    0.5825915
9  cluster_bcell_1      cluster_neutrophil_2 16    0.5669501
27 cluster_mol_2        cluster_neutrophil_2 27    0.5450988
21 cluster_ependymal_7  cluster_neutrophil_2 36    0.5418897
4  cluster_astrocyte_3  cluster_neutrophil_2 26    0.5413083
20 cluster_ependymal_6  cluster_neutrophil_2 40    0.5355406
3  cluster_astrocyte_2  cluster_neutrophil_2 24    0.5235901
7  cluster_Basophil     cluster_neutrophil_2 33    0.5081068
8  cluster_bcell_0      cluster_neutrophil_2 21    0.5058642
12 cluster_bcell_4      cluster_neutrophil_2 13    0.4747760
47 cluster_neutrophil_2 cluster_opc_5        20    0.4733461

In [ ]:
interest <- "COL4A2_ITGA3_ITGB1"
cellchat_lr <- subsetCommunication(cellchat, slot.name = "net")
cellchat_lr <- cellchat_lr[order(cellchat_lr$prob, decreasing = TRUE), ]

lr_interest <- cellchat_lr[cellchat_lr$interaction_name == interest, ]
lr_plot <- lr_interest[, c("source", "target", "prob")]

group_cell <- sort(levels(cellchat@idents))
grid_color <- scales::hue_pal()(length(group_cell))
names(grid_color) <- group_cell

min_prob <- min(lr_plot$prob)
max_prob <- max(lr_plot$prob)
col_fun <- colorRamp2(
  breaks = c(min_prob, (min_prob + max_prob)/2, max_prob),
  colors = c("#0A0F8F", "#FFEE58", "#FF0000")
)
link_colors <- col_fun(lr_plot$prob)

invisible({
  graphics.off()

  svglite::svglite(
    file.path(cellchat_dir, paste0(interest, "_lr.svg")),
    width = 9, height = 8
  )

  circos.clear()
  circos.par(
    cell.padding = c(0, 0, 0, 0),
    track.margin = c(0.01, 0.01),
    points.overflow.warning = FALSE,
    gap.after = 5
  )

  chordDiagram(
    x = lr_plot,
    order = group_cell,
    grid.col = grid_color,
    col = link_colors,
    transparency = 0.2,
    directional = 1,
    direction.type = c("diffHeight"),
    diffHeight = -0.03,
    link.sort = TRUE,
    link.largest.ontop = TRUE,
    annotationTrack = "grid",
    preAllocateTracks = list(track.height = 0.3)
  )

  circos.track(track.index = 1, panel.fun = function(x, y) {
    circlize::circos.text(
      CELL_META$xcenter,
      CELL_META$ylim[1],
      CELL_META$sector.index,

      facing = "clockwise",
      niceFacing = TRUE,
      adj = c(0, 0.5),
      cex = 0.8
    )
  }, bg.border = NA)

  lgd <- Legend(
    col_fun = col_fun,
    title = "Interaction\nStrength",
    at = c(min_prob, max_prob),
    labels = c("Low", "High")
  )
  draw(lgd, x = unit(0.9, "npc"), y = unit(0.9, "npc"))

  dev.off()
})

#### Visualize the specific signaling pathway using a Chord Diagram

In [8]:
# Identified signaling pathways
cellchat@netP$pathways

 [1] "CypA"         "APP"          "PTN"          "MK"           "GALECTIN"
 [6] "ADGRE"        "COLLAGEN"     "MIF"          "CCL"          "ICAM"
[11] "FN1"          "LAMININ"      "SPP1"         "Cholesterol"  "SELPLG"
[16] "TNF"          "ApoE"         "TGFb"         "CNTN"         "CADM"
[21] "THY1"         "THBS"         "GRN"          "JAM"          "SEMA4"
[26] "CXCL"         "PTPRM"        "CD80"         "LAIR1"        "VEGF"
[31] "PROS"         "SEMA7"        "Testosterone" "PECAM1"       "CSF"
[36] "ADGRG"        "SELL"         "COMPLEMENT"   "CD39"         "VISFATIN"
[41] "PECAM2"       "CysLTs"       "L1CAM"        "MPZ"          "MAG"
[46] "Netrin"       "AGRN"         "Desmosterol"  "ANNEXIN"      "PLAU"
[51] "NOTCH"        "CHEMERIN"     "DHT"          "TWEAK"        "SEMA3"
[56] "12oxoLTB4"    "DHEA"         "NRG"          "IL1"          "Adenosine"
[61] "ANGPTL"       "DHEAS"        "ncWNT"        "GDF"          "LXA4"

In [ ]:
interest <- "SerotoninDopamin"
cellchat_pathway <- subsetCommunication(cellchat, slot.name = "netP") # slot.name = "net" -> slot.name = "netP"
cellchat_pathway <- cellchat_pathway[order(cellchat_pathway$prob, decreasing = TRUE), ]

pathway_interest <- cellchat_pathway[cellchat_pathway$pathway_name == interest, ] # $interaction_name -> $pathway_name
pathway_plot <- pathway_interest[, c("source", "target", "prob")]

group_cell <- levels(cellchat@idents)
grid_color <- scales::hue_pal()(length(group_cell))
names(grid_color) <- group_cell

min_prob <- min(pathway_plot$prob)
max_prob <- max(pathway_plot$prob)
col_fun <- colorRamp2(
  breaks = c(min_prob, (min_prob + max_prob)/2, max_prob), 
  colors = c("#0A0F8F", "#FFEE58", "#FF0000") 
)
link_colors <- col_fun(pathway_plot$prob)

invisible({
  graphics.off()

  svglite::svglite(
    file.path(cellchat_dir, paste0(interest, "_pathway.svg")),
    width = 9, height = 8
  )

  circos.clear()
  circos.par(
    cell.padding = c(0, 0, 0, 0),
    track.margin = c(0.01, 0.01),
    points.overflow.warning = FALSE,
    gap.after = 5
  )

  chordDiagram(
    x = pathway_plot,
    grid.col = grid_color,
    col = link_colors,
    transparency = 0.2,
    directional = 1,
    direction.type = c("diffHeight"),
    diffHeight = -0.03,
    link.sort = TRUE,
    link.largest.ontop = TRUE,
    annotationTrack = "grid", 
    preAllocateTracks = list(track.height = 0.3)
  )

  circos.track(track.index = 1, panel.fun = function(x, y) {
    circlize::circos.text(
      CELL_META$xcenter, 
      CELL_META$ylim[1], 
      CELL_META$sector.index, 
      
      facing = "clockwise",
      niceFacing = TRUE,
      adj = c(0, 0.5),
      cex = 0.8
    )
  }, bg.border = NA)
  
  lgd <- Legend(
    col_fun = col_fun, 
    title = "Interaction\nStrength", 
    at = c(min_prob, max_prob), 
    labels = c("Low", "High")
  )
  draw(lgd, x = unit(0.9, "npc"), y = unit(0.9, "npc"))

  dev.off()
})

In [9]:
cellchat_pathway <- subsetCommunication(cellchat, slot.name = "netP")
cellchat_pathway <- cellchat_pathway[cellchat_pathway$prob > 0, ]

cellchat_pathway$source <- as.character(cellchat_pathway$source)
cellchat_pathway$target <- as.character(cellchat_pathway$target)

pathway_count <- aggregate(
  pathway_name ~ source + target,
  data = cellchat_pathway,
  FUN = function(x) length(unique(x))
)

pathway_weight <- aggregate(
  prob ~ source + target,
  data = cellchat_pathway,
  FUN = sum
)

pair_pathway_directed <- merge(
  pathway_count,
  pathway_weight,
  by = c("source", "target")
)

colnames(pair_pathway_directed) <- c(
  "source", "target", "pathway_count", "weight"
)

pair_pathway_directed <- pair_pathway_directed[
  pair_pathway_directed$source != pair_pathway_directed$target,
]

pair_pathway_undirected <- transform(
  pair_pathway_directed,
  cell1 = pmin(source, target),
  cell2 = pmax(source, target)
)

pair_pathway_undirected <- aggregate(
  cbind(pathway_count, weight) ~ cell1 + cell2,
  data = pair_pathway_undirected,
  FUN = sum
)

pair_pathway_undirected <- pair_pathway_undirected[
  order(
    pair_pathway_undirected$pathway_count,
    pair_pathway_undirected$weight,
    decreasing = TRUE
  ),
]

head(pair_pathway_undirected, 30)

    cell1                                 cell2
8   cluster_ANC_Microglia                 cluster_AntigenPresenting_Microglia
155 cluster_ANC_Microglia                 cluster_Monocyte
158 cluster_AntigenPresenting_Microglia   cluster_Monocyte
82  cluster_AntigenPresenting_Cycling_OPC cluster_Endothelial
110 cluster_AntigenPresenting_Microglia   cluster_Epithelial
80  cluster_ANC_Microglia                 cluster_Endothelial
83  cluster_AntigenPresenting_Microglia   cluster_Endothelial
19  cluster_AntigenPresenting_Cycling_OPC cluster_AntigenPresenting_OPC
85  cluster_AntigenPresenting_OPC         cluster_Endothelial
119 cluster_Endothelial                   cluster_Epithelial
107 cluster_ANC_Microglia                 cluster_Epithelial
167 cluster_Endothelial                   cluster_Monocyte
175 cluster_AntigenPresenting_Cycling_OPC cluster_Neuron
3   cluster_ANC_Microglia                 cluster_ANC_Neutrophil
169 cluster_Epithelial                    cluster_Monocyte
109 cluster_AntigenPresenting_Cycling_OPC cluster_Epithelial
171 cluster_MoDC_new                      cluster_Monocyte
138 cluster_ANC_Microglia                 cluster_MoDC_new
5   cluster_ANC_Microglia                 cluster_AntigenPresenting_Cycling_OPC
178 cluster_AntigenPresenting_OPC         cluster_Neuron
10  cluster_AntigenPresenting_Cycling_OPC cluster_AntigenPresenting_Microglia
392 cluster_Endothelial                   cluster_vSMC
365 cluster_Endothelial                   cluster_VLMC
9   cluster_ANC_Neutrophil                cluster_AntigenPresenting_Microglia
20  cluster_AntigenPresenting_Microglia   cluster_AntigenPresenting_OPC
353 cluster_ANC_Microglia                 cluster_VLMC
185 cluster_Endothelial                   cluster_Neuron
355 cluster_AntigenPresenting_Cycling_OPC cluster_VLMC
156 cluster_ANC_Neutrophil                cluster_Monocyte
79  cluster_ANC_Astrocyte                 cluster_Endothelial
    pathway_count weight
8   46            2.7403368
155 45            3.2742680
158 45            3.0944590
82  39            1.5896995
110 39            1.0270033
80  38            1.8895033
83  38            1.8614130
19  38            1.6095274
85  37            1.6579467
119 37            1.5333632
107 36            0.9639607
167 35            2.2688928
175 35            0.8209659
3   34            1.9677105
169 34            1.2595824
109 34            1.0870200
171 33            1.8921210
138 33            1.8019887
5   33            1.4017337
178 33            0.8766139
10  32            1.4881187
392 32            1.4683431
365 32            1.1874219
9   31            1.8110908
20  31            1.4610262
353 31            1.1154211
185 31            0.9790117
355 31            0.9242939
156 30            2.1681080
79  30            1.5985710